services:
  - type: web
    name: aichatpalbot
    env: python
    plan: free
    headers:
      - key: X-Forwarded-Proto
        value: https
    buildCommand: "pip install --break-system-packages -r requirements.txt"
    startCommand: "python3 main.py"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-pro
      - key: GEMINI_SYSTEM_PROMPT
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
    autoDeploy: true
    healthCheckPath: "/"